package Interface;

import batalhanaval.BatalhaNavalCliente;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/*
 * InterfaceBatalhaNaval.java
 *
 * Created on 23/05/2012, 19:36:12
 */
/**
 *
 * @author Larissa
 */
public class InterfaceBatalhaNaval extends javax.swing.JFrame {

    private BatalhaNavalCliente cliente;

    /**
     * Creates new form InterfaceBatalhaNaval
     */
    public InterfaceBatalhaNaval() {
        initComponents();
        String url = "//localhost:1099/batalhanaval";
        try {
            cliente = new BatalhaNavalCliente(url);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "O servidor não foi encontrado.");
            System.exit(1);
        }
        this.getRootPane().setDefaultButton(btnAtacar);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textCampos = new javax.swing.JTextPane();
        btnAtacar = new javax.swing.JButton();
        digita_coordenada = new javax.swing.JLabel();
        textCoordenada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalha Naval");
        setName("mainFrame");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        textCampos.setBorder(null);
        textCampos.setEditable(false);
        textCampos.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textCampos.setAlignmentX(1.0F);
        textCampos.setAlignmentY(1.0F);
        textCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textCampos.setFocusable(false);
        jScrollPane1.setViewportView(textCampos);

        btnAtacar.setText("ATACAR");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        digita_coordenada.setText("Digite a coordenada de ataque:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textCoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(digita_coordenada, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digita_coordenada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        
        String coordenada = textCoordenada.getText();
        if (coordenada.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a coordenada de ataque.");
            return;
        }
        
        try {
            cliente.atacar(coordenada);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        
        textCampos.setText(cliente.getUltimoCampo());
        JOptionPane.showMessageDialog(this, cliente.getUltimaMensagem());
        
    }//GEN-LAST:event_btnAtacarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        esperar();
        
        String nome = "";
        while (nome.trim().isEmpty()) {
            nome = JOptionPane.showInputDialog(this, "Informe o seu nome:", "Nome do Jogador");
            if (nome == null) {
                System.exit(0);
            }
        }

        List<String> list = cliente.getOrdemNavios();

        try {
            for (String navio : list) {
                String coordenada = JOptionPane.showInputDialog(this, "Informe a coordenada para " + navio + ":");
                if (coordenada == null) {
                    System.exit(0);
                }
                cliente.adicionarCoordenadas(coordenada);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
        try {
            cliente.jogar(nome);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
        this.setTitle(this.getTitle() + " ~ " + nome);
        textCampos.setText(cliente.getUltimoCampo());
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JLabel digita_coordenada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textCampos;
    private javax.swing.JTextField textCoordenada;
    // End of variables declaration//GEN-END:variables

    private void esperar() {
        textCampos.setText("Eperando jogadores...");
    }
    
    private void pronto() {
        textCampos.setText("Esperando jogadores... Pronto!");
    }
    
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceBatalhaNaval().setVisible(true);
            }
        });
    }
}
